export class OurCoffeePage {
    browseOurCoffeesButton = '//a[@class="sb-button sb-button--positive mt5"]'
    productRoastTab = '#product_roast'
    darkRoastProduct = '//*[2][@data-drupal-facet-id="product_roast"]/li[3]'
    darkRoastCheckbox = '#product-roast-29'
    productOriginTab = '#product_origin'
    latinAmericaProduct = '//*[2][@data-drupal-facet-id="product_origin"]/li[1]'
    latinAmericaCheckbox = '#product-origin-34'
    productFormatTab = '#product_formats'
    wholeBeanProduct = '//*[2][@data-drupal-facet-id="product_formats"]/li[3]'
    wholeBeanCheckbox = '#product-formats-63'
    italianRoastWholeBeanProduct = 'a[href*="/products/italian-roast-whole-bean"]'
    titleContainer = '.title-container'
    whereToBuyButton = '//*[@class="search-lang-container"]//a[contains(@href, "/store-locator")]'
}